# Ejercicio 3

3. Con el uso de DEAP, resolver el anterior ejercicio.

Importando librerias:

In [1]:
import random
import numpy 
from deap import algorithms
from deap import base
from deap import creator
from deap import tools
import pandas as pd

Leyendo archivo csv:

In [2]:
NB_QUEENS = 5
data= pd.read_csv("recorrido.csv", sep=",", header=None)
array=numpy.asarray(data)
recorrido= data.iloc[:, :].values
nodos=["a","b","c","d","e"]

Funciones:

In [3]:
def comienzo(nodos,comienzo):
    longitud=len(nodos)
    indice=-1
    for i in range(longitud):
        if(nodos[i]==comienzo):
            return i
def mostrarcamino(ordenado):
    longitud=len(ordenado)
    sum=0
    for i in range(longitud):
        print(nodos[ordenado[i]],'-> ',end="")
    print(nodos[ordenado[0]])
def mostrarcostos(individual):
    longitud=len(individual)
    sum=0
    for i in range(longitud-1):
        print(recorrido[individual[i]][individual[i+1]],'   ',end="")
    print(recorrido[individual[i+1]][individual[0]])
def mostrarnodos(vec):
    for i in vec:
        print(i,' ',end="")
    print()
def evaluaPosicion(individual):
    longitud=len(individual)
    sum=0
    for i in range(longitud-1):
        sum=sum+recorrido[individual[i]][individual[i+1]]
    sum=sum+recorrido[individual[i+1]][individual[0]]
    return sum,

def principio(individual,a):
    longitud=len(individual)
    indice=0
    for i in range(longitud):
        if(individual[i]==a):
            indice=i
    ordenado=individual[indice:]+individual[:indice]
    return ordenado

In [4]:
creator.create("FitnessMin", base.Fitness, weights=(-1.0,))
creator.create("Individual", list, fitness=creator.FitnessMin)

toolbox = base.Toolbox()
toolbox.register("permutation", random.sample, range(NB_QUEENS), NB_QUEENS)

toolbox.register("individual", tools.initIterate, creator.Individual, toolbox.permutation)
toolbox.register("population", tools.initRepeat, list, toolbox.individual)

toolbox.register("evaluate", evaluaPosicion)
toolbox.register("mate", tools.cxPartialyMatched)
toolbox.register("mutate", tools.mutShuffleIndexes, indpb=2.0/NB_QUEENS)
toolbox.register("select", tools.selTournament, tournsize=3)

Main:

In [6]:
def main(seed=0):
    random.seed(seed)
    pop = toolbox.population(n=300)
    hof = tools.HallOfFame(1)
    stats = tools.Statistics(lambda ind: ind.fitness.values)
    stats.register("Avg", numpy.mean)
    stats.register("Std", numpy.std)
    stats.register("Min", numpy.min)
    stats.register("Max", numpy.max)

    algorithms.eaSimple(pop, toolbox, cxpb=0.5, mutpb=0.2, ngen=100, stats=stats,
                        halloffame=hof, verbose=False)
    print()
    print('Nodos :')
    mostrarnodos(nodos)
    print('Recorridos :')
    print(recorrido)
    print('Introduce por favor el nodo de inicio')
    nodo=str(input()).lower()
     
    while nodo==-1:
        print('El nodo no existe por favor ingresa uno válido')
        nodo=input()
    
    inicio=comienzo(nodos, nodo)
    vector=principio(pop[0], inicio)
    print('Mejor recorrido suma :', evaluaPosicion(pop[0])[0])
    mostrarcamino(vector)
    print("  ",end="")
    mostrarcostos(vector)
    
    return pop, stats, hof

if __name__ == "__main__":
    pop, stats, hof=main()
   
    


Nodos :
a  b  c  d  e  
Recorridos :
[[ 0  7  9  8 20]
 [ 7  0 10  4 11]
 [ 9 10  0 15  5]
 [ 8  4 15  0 17]
 [20 11  5 17  0]]
Introduce por favor el nodo de inicio
a
Mejor recorrido suma : 37
a -> d -> b -> e -> c -> a
  8    4    11    5    9
